package com.nonlinearlabs.NonMaps.client.world.overlay.belt.presets;

import com.google.gwt.canvas.dom.client.Context2d;
import com.google.gwt.event.dom.client.KeyDownEvent;
import com.nonlinearlabs.NonMaps.client.NonMaps;
import com.nonlinearlabs.NonMaps.client.ServerProxy.DownloadHandler;
import com.nonlinearlabs.NonMaps.client.world.AppendOverwriteInsertPresetDialog;
import com.nonlinearlabs.NonMaps.client.world.AppendOverwriteInsertPresetDialog.Action;
import com.nonlinearlabs.NonMaps.client.world.AppendOverwriteInsertPresetDialog.Handler;
import com.nonlinearlabs.NonMaps.client.world.Control;
import com.nonlinearlabs.NonMaps.client.world.Gray;
import com.nonlinearlabs.NonMaps.client.world.Position;
import com.nonlinearlabs.NonMaps.client.world.Rect;
import com.nonlinearlabs.NonMaps.client.world.maps.presets.PresetManager;
import com.nonlinearlabs.NonMaps.client.world.overlay.OverlayLayout;
import com.nonlinearlabs.NonMaps.client.world.overlay.SVGImage;
import com.nonlinearlabs.NonMaps.client.world.overlay.SVGImagePhase;
import com.nonlinearlabs.NonMaps.client.world.overlay.belt.EditBufferDraggingButton;

class StorePreset extends SVGImage {

	class DraggableButtonPhase extends SVGImagePhase implements EditBufferDraggingButton {

		public DraggableButtonPhase(SVGImage parent, String imageName) {
			super(parent, imageName);
		}

	}

	StorePreset(OverlayLayout parent) {
		super(parent, "Store_Enabled.svg", "Store_Drag.svg", "Store_Disabled.svg");
	}

	@Override
	public int getSelectedPhase() {
		if (isCaptureControl() || isDraggingControl()) {
			return 1;
		}

		return 0;
	}

	@Override
	protected SVGImagePhase createPhase(String s) {
		return new DraggableButtonPhase(this, s);
	}

	@Override
	public Control startDragging(Position eventPoint) {

		return getNonMaps().getNonLinearWorld().getViewport().getOverlay().createDragProxy(getPhase(1), getPixRect().getPosition());
	}

	@Override
	public Control click(Position eventPoint) {
		boolean hasSelectedBank = getPresetManager().hasSelectedBank();

		if (!hasSelectedBank)
			createNewBank();
		else
			storeToBank();

		return this;
	}

	protected PresetManager getPresetManager() {
		return getNonMaps().getNonLinearWorld().getPresetManager();
	}

	public void storeToBank() {
		final String currentName = NonMaps.theMaps.getNonLinearWorld().getParameterEditor().getLoadedPresetName();

		NonMaps.theMaps.getServerProxy().getUniquePresetName(currentName, new DownloadHandler() {

			@Override
			public void onFileDownloaded(String text) {
				openStoreDialog(currentName, text);
			}

			@Override
			public void onError() {
				openStoreDialog(currentName, currentName);
			}
		});
	}

	private void openStoreDialog(String name, String autoGeneratedName) {
		AppendOverwriteInsertPresetDialog.open(name, autoGeneratedName, new Handler() {

			@Override
			public void onActionChoosen(String newName, String info, Action action) {
				handleDialogAction(action, newName, info);
			}
		});
	}

	protected void createNewBank() {
		getNonMaps().getServerProxy().newBankFromEditBuffer(getNonMaps().getNonLinearWorld().getNonPosition().getCenterPoint());
	}

	@Override
	public void draw(Context2d ctx, int invalidationMask) {
		if (isDraggingControl() && !isVisibilityForced()) {
			drawDetachedState(ctx);
		} else {
			super.draw(ctx, invalidationMask);
		}
	}

	protected void drawDetachedState(Context2d ctx) {
		Rect r = getPixRect().copy();
		double reduced = 0;
		r.reduceHeightBy(reduced);
		r.reduceWidthBy(reduced);
		r.drawRoundedArea(ctx, 2, 1, new Gray(26), new Gray(0));
	}

	protected void handleDialogAction(Action action, String newName, String info) {
		switch (action) {
		case APPEND:
			getNonMaps().getServerProxy().appendPreset(newName, info);
			break;

		case INSERT:
			getNonMaps().getServerProxy().insertPreset(newName, info);
			break;

		case OVERWRITE:
			getNonMaps().getServerProxy().overwritePreset(newName, info);
			break;

		default:
			break;
		}
	}

	@Override
	public Control onKey(KeyDownEvent event) {
		if (event.getNativeKeyCode() == com.google.gwt.event.dom.client.KeyCodes.KEY_S && event.isControlKeyDown()) {
			storeToBank();
			return this;
		}
		return super.onKey(event);
	}
}
